- name: Install bind and evolution packages
  hosts: n01538887-c-vm1
  become: yes

  tasks:
  - name: Install bind package
    yum:
      name: "{{ bind_package }}"
      state: present
    register: bind_package_output

  - name: Install evolution package
    yum:
      name: "{{ evolution_package }}"
      state: present
    register: evolution_package_output

  - name: Display entire task outputs from the previous steps
    debug:
      msg:  >
        Task outputs: {{  bind_package_output }}  and {{  evolution_package_output }}

  - name: Display reults of the installed packages
    debug:
      msg: >
        Names of the packages that were installed: {{  bind_package_output['results'] }}  
        and {{  evolution_package_output['results'] }} 