---
- name: Add group cloudadmins
  group:
    name: "{{ group_name }}"
    state: present

- name: Add user accounts
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    generate_ssh_key: no
  loop: "{{ users }}"

- name: Generate SSH key for the current user
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/{{ ansible_user }}_id_rsa"
  register: user_info

- name: Create .ssh directory for users
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ users }}"

- name: Ensure authorized_keys file exist
  file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0600
    state: touch
  loop: "{{ users }}"


- name: Distribute SSH keys for users from the current user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key:  "{{ user_info.ssh_public_key }}"
  loop: "{{ users }}"

- name: Ensure PubkeyAuthentication is set to yes in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PubkeyAuthentication"
    line: "PubkeyAuthentication yes"
    state: present
  become: true

- name: Add SSH key configuration to .ssh/config using blockinfile
  blockinfile:
    path: "/home/{{ ansible_user }}/.ssh/config"
    block: |
      Host {{ item.name }}
        HostName {{ inventory_hostname }}.canadaeast.cloudapp.azure.com
        User {{ item.name }}
        IdentityFile /home/{{ ansible_user }}/.ssh/{{ ansible_user }}_id_rsa
    marker: "# {mark} ANSIBLE MANAGED BLOCK for {{ item.name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    create: yes
  loop: "{{ users }}"